Algoritmo "senha fixa ENQ"

// Seção de Declarações das variáveis
 var
 senha: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreva("Digite a Senha: ")
  leia (senha)
  enquanto senha <> 2002 faca
           escreva ("Senha inválida! Tente novamente: ")
           leia (senha)
  fimenquanto
             se senha = 2002 entao
              escreval ("Acesso Permitido!")
           fimse

Fimalgoritmo